### ISSUE TITLE
Missing changes in deployment of docs site 

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/doc.silverstripe.org#170]
A few of my web accessibility P.R's from silverstripe-docsviewer have been somehow missed through the deployment of docs.silverstripe.org

Example image misalignment: https://github.com/silverstripe/silverstripe-docsviewer/pull/141
#
Live site: ![image](https://user-images.githubusercontent.com/24258161/33244431-e7a1f7a2-d35b-11e7-9978-da156fdb6302.png)

cc @be2n 

---

Sacha's docsviewer pull requests (edited in):

Deployed:
- [x] silverstripe/silverstripe-docsviewer#139
- [x] silverstripe/silverstripe-docsviewer#140

Missing from deployment:
- [x] silverstripe/silverstripe-docsviewer#141
- [x] silverstripe/silverstripe-docsviewer#142

**Comment by robbieaverill** [comment]
Yeah, we just need to deploy the latest changes to production: https://github.com/silverstripe/silverstripe-docsviewer/compare/2.0.0-beta8...2.0.0-rc1

**Comment by robbieaverill** [comment]
Done!

**Comment by sachajudd** [comment]
Cheers!
